### ISSUE TITLE
Producer Profile: View buying info and links (clarify logic for contact form)

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#11]
Needs test data to make sure we have all the scenarios represented

Test Data:
* Wholesale and Household - Bundarra, one link each; 
* Only Household - Murrnong, one link
* No links - Pukawidgee (come through after caching). NB. I left the household box ticked but emptied all text fields and links 

Changes needed
[] Add Contact Producer Button
[] ? Wholesale Customers title 

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/188ee59a-9b0d-4618-afc3-d03aa0c771f2)

**Comment by JbPasquier** [comment]
I don't understand what needs to change here? Can you clarify, please?

**Comment by mariocarabotta** [comment]
> I don't understand what needs to change here? Can you clarify, please?

You can find different scenarios mocks and annotations [here](https://www.figma.com/file/jCheM9rB3tzfdPyIZcmcM9/Engineering-Delivery---Discover-Regenerative?type=design&node-id=307%3A4&mode=design&t=pAtyVt2XhaoXHZxf-1). 

Feel free to let me know if you need further details

**Comment by mariocarabotta** [comment]
also, I'm noticing this icon? not sure why it's there since we don't have whatsapp links
https://ofn-rpp.startinblox.com/regenerative-produce-portal-producer-details/@https%3A//api.regenerative.org.au/webhook/regen/producer%3Fid%3DrecmepDXsFPzYibCv@

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/ebbb69eb-3487-40f3-acca-35463c38d924)

**Comment by mariocarabotta** [comment]
[here](https://ofn-rpp.startinblox.com/regenerative-produce-portal-producer-details/@https%3A//api.regenerative.org.au/webhook/regen/producer%3Fid%3Drecy8pAfR9h34WYZR@) I'm seeing multiple facebook links. @mkllnk looping you in since we might need to handle it our side?

**Comment by JbPasquier** [comment]
> You can find different scenarios mocks and annotations [here](https://www.figma.com/file/jCheM9rB3tzfdPyIZcmcM9/Engineering-Delivery---Discover-Regenerative?type=design&node-id=307%3A4&mode=design&t=pAtyVt2XhaoXHZxf-1).

This is the document I based the implementation on. If anything is wrong, maybe it's worth checking related datas.

Can you point some producers which have wrong display?

> also, I'm noticing this icon? not sure why it's there since we don't have whatsapp links

Datas have.

**Comment by mkllnk** [comment]
I just checked that link and I could see only one Facebook link now. Maybe fixed?

**Comment by kirstenalarsen** [comment]
@JbPasquier the problem as I see it is that 

## 1. 'Wholesale Customers' title not displaying
when Wholesale Customers is on, there should be a title INSIDE the box, between How to Buy and the info, as per mockup 

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/02a724b2-86d1-4fe2-8a1e-b6d4be087383)

Looking at Bundarra, the wholesale customer info is there but the TITLE is missing 

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/2911176/8786c493-26a0-4004-bf52-245c57eba055)

## 2. View Contact Details button missing

Underneath the Wholesale Customer section there should be a button that takes the User down to the contact form

**Comment by kirstenalarsen** [comment]
just looking for different cases for this - Grazed and Grown is not displaying any 'how to buy' section at all - can anyone see why this might be? https://regenerative.org.au/regenerative-produce-portal-producer-details/@https%3A//api.regenerative.org.au/webhook/regen/producer%3Fid%3Drec2aFRu0H3Czf2IG@ @mkllnk @mariocarabotta @JbPasquier

**Comment by JbPasquier** [comment]
> Looking at Bundarra, the wholesale customer info is there but the TITLE is missing

Fixed

> Underneath the Wholesale Customer section there should be a button that takes the User down to the contact form

The mockup said this:
![image](https://github.com/openfoodfoundation/sib-discovery-components/assets/14278890/43531123-ece2-4d9b-bd2c-ba2c51c8c781)

In your datas, Bundarra does not have `phone` enabled.

> Grazed and Grown is not displaying any 'how to buy' section at all - can anyone see why this might be

This producer have no product. That's the condition I've made to display the whole How to buy block to avoid empty screen. Should I remove this check?

**Comment by mariocarabotta** [comment]
> This producer have no product. That's the condition I've made to display the whole How to buy block to avoid empty screen. Should I remove this check?

Please remove the check. It will look empty, but we will encourage producers to add products, so it should not happen frequently.

@JbPasquier we have discussed internally about always showing the contact form - hopefully this might simplify the logic a little bit.

I have prepared some examples of how that would look like [here](https://www.figma.com/file/jCheM9rB3tzfdPyIZcmcM9/Engineering-Delivery---Discover-Regenerative?type=design&node-id=496%3A202&mode=design&t=n9Lo2Oia6Cab0yN2-1)

- always assume you are going to get an email address
- the email address will be used to send the message from the form (this might be with Maikel maybe)
- always show the How to buy section
- always show the button that anchors to the contact for
- always show the contact form
- if people have the flag email, then show the email
- if people have the flag phone, then show phone
- if both, show both
- if none, hide container left of the contact form

**Comment by JbPasquier** [comment]
Done!

> It will look empty, but we will encourage producers to add products, so it should not happen frequently.

I hope so, some like the Tak-One Organics producer page are rather deceptive.

> the email address will be used to send the message from the form (this might be with Maikel maybe)

That's with Maikel, indeed. It seems that it's already done.

**Comment by mariocarabotta** [comment]
> I hope so, some like the Tak-One Organics producer page are rather deceptive.

agree! there are a couple of people in the team helping out producers filling their profile. Also, at the moment the profiles that are still in progress get published for our testing, but before we go live we'll hide the ones that are not ready.

thanks for updating this! I went through most of the profiles, just a few prodycers still show the phone number at the top below the button. it might be some logic from the previous design iteration (sorry about that!).
if you could remove it, that would be great. we would like to show phone number and email address ONLY next to the contact form.

a couple of examples of where this is happening here > Grazed and Grown Farm, Moyarra Pastoral

![Screenshot 2024-03-26 at 10 20 00](https://github.com/openfoodfoundation/sib-discovery-components/assets/6696729/deda1b63-3327-432f-a72c-f2501da92bdf)

**Comment by JbPasquier** [comment]
Found, thanks. Fixed.

**Comment by mariocarabotta** [comment]
working great! moving to done 👏
