### ISSUE TITLE
How to change labels/headings for filter menu?

### ISSUE THREAD

**Issue by karlafalk** [openfoodfoundation/sib-discovery-components#68]
Exploring how we can change the text labels for the filter headings on the wordpress page?

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/58d99d82-739d-4318-acf1-2c1c8a66e310)

Would this be in the 'Show assurance, list classifications, options' workflow code nodes? I hesitate to change something in the code in case it breaks the workflow.  I am assuming if we change column headings in the Airtable base it won't get read correctly in the code, so we shouldn't try making changes to the Airtable column headings?

**Comment by karlafalk** [comment]
@mkllnk Just noting that understanding how we can edit these labels is the next priority for the tech aspects of the Waterloo Project.  Thanks!

**Comment by mkllnk** [comment]
There are a few options:

1. Use smaller parts of the component and change the labels there.
2. Fork the component and create a version with your text.
3. Add some Javascript which changes the text.

I haven't investigated how much work the first option would be. But if we are only talking about a few words then option 3 seems to be the most attractive. Can you tell me the new text and I'll provide you with code for the Wordpress site?

**Comment by karlafalk** [comment]
Thanks @mkllnk for that info. Looking at this more closely, ideally we would be able to modify how the component displays in few other ways.  Here is a mockup of our wishlist modifications:

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/dca6547e-e5ab-4bf2-a73f-3f0d61243b05)

Our top priorities would be to: 

1) Move the 'Assurance Partners' filter menu to a top menu and have all the 3 options visible (no dropdown) along with a 'show all' option. This would remove the need to change the 'Assurance Partners' text as we wouldn't be using this category heading.
2) Change the 'First Nations Led' text on the left hand menu to 'Indigenous Led' and change the flag icon to one relevant for Canada.
3) Modify one of the other Filter menus (maybe Certifications) and add it back into the component to allow the Waterloo Directory to additionally be sorted by a 'Category' field (to replace the category heading of 'Certifications'), and have options all be displayed instead of a drop down menu.  
4) Specify how many profiles to show before loading more.

Can you let us know how feasible these changes would be, what would be involved, and how long they would take to implement? Thanks!

**Comment by mkllnk** [comment]
Changing labels and text should be relatively easy. So that would be point 2. But moving things around and changing the type of input field (select vs dropdown) is a dev task that would require us to create a copy of the current component and develop it alongside it, increasing maintenance cost. So I think that point 1 is too expensive.

Point 3: I'm not sure how this is supposed to work. In our component, enterprises can select produce type and be filtered by that, for example, meat or fruit. But it requires input to Airtable which would be manual in your case.

Point 4: This is a bit more tricky. I need to check the code.

**Comment by mkllnk** [comment]
Hm, I just experimented with changing some of the text and it's trickier than I thought. I managed to replace the First Nations part though. You can replace the `style` block with this code to achieve it:
```html
<style>
div.row[name="set-line-produce"] { display: none }

custom-search-firstnationsled label {
  color: white !important;
}

custom-search-firstnationsled label:before {
  content: "Indigenous Led";
  color: black;
  display: block;
  position: absolute;
}
</style>
```

I confirmed that changing the flag icon is very easy though. Can you supply me with one?

Anything that goes beyond text or image changes, would need at least a whole day of work from me. I reckon that Startin'Blox could do a better and quicker job though. Let's get a quote from them.

**Comment by karlafalk** [comment]
Ok Thanks @mkllnk for addressing those items.  We will look into getting a quote from Startin'Blox (@David-OFN-CA) for changes that require moving things around or changing the type of input field.

> Point 3: I'm not sure how this is supposed to work. In our component, enterprises can select produce type and be filtered by that, for example, meat or fruit. But it requires input to Airtable which would be manual in your case.

Yes, the inputs into Airtable would be manual (not through OFN) for this - we would have the users fillout a form to get the data to be inputed into the 'Certifying body' field in Airtable to reflect our Categories.   Then presumably the n8n workflow would work the same to move the data to the wordpress site?  And then we would also need to change the text label as you described above with a the style edit.  

<img width="1776" alt="Screenshot 2024-06-11 at 9 09 14 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/400cc7eb-5954-4c26-9afa-cb926b3a578d">

<img width="657" alt="Screenshot 2024-06-11 at 9 22 50 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/b30d05e4-3ed6-4649-ad02-86f6a6ffdc1a">

**Comment by mkllnk** [comment]
> we would have the users fillout a form to get the data to be inputed into the 'Certifying body' field in Airtable to reflect our Categories.

That's how we do it. But we use Miniextensions for this form and it's very expensive. Maybe you can find a better solution. I thought that you were trying to avoid an additional form.

**Comment by karlafalk** [comment]
> That's how we do it. But we use Miniextensions for this form and it's very expensive. Maybe you can find a better solution. I thought that you were trying to avoid an additional form.

Yes, we would use a simpler form builder ([Fillout](https://www.fillout.com)) that we have used before.  It is not as powerful as Miniextensions, but should be adequate enough for our purposes, and easily integrates with Airtable.

**Comment by David-OFN-CA** [comment]
Okay - thanks guys - I'm going to loop Alex in now and get a quote from him

**Comment by karlafalk** [comment]
@mkllnk While we wait for a quote from Startin'Blox, I thought I would try and add in the Certification menu to our wordpress site.   

I have done this but am not sure how to get rid of the menu with all the AUS regen options (Organic, Biodynamic, etc.).  I have tried changing the code of workflow - 'List certification options', the code - node from:
<img width="995" alt="Screenshot 2024-06-19 at 7 12 56 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/6fb09b23-1ed2-41d5-8b49-edf1338ac0a3">

to this:

<img width="994" alt="Screenshot 2024-06-19 at 7 39 32 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/18231928-95e7-4e34-a61c-a653ed9fd96f">

But this doesn't seem to change the options on the wordpress site:

<img width="1544" alt="Screenshot 2024-06-19 at 5 17 11 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/4c299d24-8a6e-4897-b7dd-c515fa61341f">

Also, I am not really sure how the certifications get linked from Airtable into the wordpress:

<img width="1172" alt="Screenshot 2024-06-19 at 7 41 33 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/fed508cf-65ce-4934-8697-9efb23a1a336">

<img width="988" alt="Screenshot 2024-06-19 at 7 41 24 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/d7d138bd-cb6a-4b12-867d-cf8bd72278e3">

Which n8n workflow is responsible for moving this info from Airtable to the wordpress site? It doesn't seem to work the same as with the Assurance Partners?

**Comment by karlafalk** [comment]
@mkllnk I just wanted to give you an update.  I couldn't figure out how to adapt the certification filter menu to filter buy the 'certifying body' field in airtable, so I tried a different approach of using 'Produce Category' as our group type filter.  So please disregard the previous question about modifying certifications.  This looks like a more straightforward modification.


![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/87b6606d-5d66-44ab-aec8-64e4789ff6d6)

One question I had was why we are getting 'undefined' for the state code when we have text in that field for our 2 producers?

I was also wondering how we can eliminate the duplication display on the Producers Page?

![Image](https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/b344211c-60d3-4ef5-a1aa-6ced8a759f99)

Thanks!

**Comment by mkllnk** [comment]
@karlafalk, I think that you just didn't wait long enough for the certification options to come through. I just added them on this page:

* https://regenerative.org.au/canada-test/

For that, I added this attribute:
```
      range-producer-certifications="https://api.regenerative.org.au/webhook/regen_CAN/certifications"
```

The filter doesn't work yet though. I don't see any certifications on the producer. In Airtable, that is an assurance of Type `certification`. It needs a certified enterprise, a certifying body etc. The field `Certification status` contains values like _Organic_ in Australia but you can put something else in there. It needs to match the filter options. And currently, each certification can have only one status, otherwise the filter doesn't work.

**Comment by mkllnk** [comment]
But if you want to use the produce types, which is much simpler, then the `undefined` value was due to a bug in the workflow. It didn't encode the ampersand `&` properly. I hope I fixed it but I won't be able to test it today.

**Comment by karlafalk** [comment]
> In Airtable, that is an assurance of Type `certification`. It needs a certified enterprise, a certifying body etc. The field `Certification status` contains values like _Organic_ in Australia but you can put something else in there. It needs to match the filter options. And currently, each certification can have only one status, otherwise the filter doesn't work.

Thanks @mkllnk I think I didn't have all the fields in Airtable filled properly before.  Regardless I think that the produce type category might work better for us.  It is good to have the options though too.

**Comment by karlafalk** [comment]
Hello @mkllnk  I just wanted to make sure that we are able to change the labels for the filter options of the Waterloo directory.  Would we be able to change the label  'Produce Types' to 'Services Offered'?

Previously you had changed the text 'First Nations Led' to 'Indigenous Led' with this edit to the style code:


#> <style>
> div.row[name="set-line-produce"] { display: none }
> 
> custom-search-firstnationsled label {
>   color: white !important;
> }
> 
> custom-search-firstnationsled label:before {
>   content: "Indigenous Led";
>   color: black;
>   display: block;
>   position: absolute;
> }
> </style>

So I imagine it is something similar? Thanks!

**Comment by karlafalk** [comment]
Also @mkllnk can we have the First Nations/Indigenous flag removed altogether from that toggle?  Thanks!

**Comment by karlafalk** [comment]
@mkllnk Just to follow up here.  Since we are moving forward with forking the components for the Waterloo Project, maybe we will hold of on troubleshooting these last 2 items (changing the 'Produce types' label and removing the Indigenous flag), and they might get taken care of as part of that work.

**Comment by karlafalk** [comment]
Also @mkllnk I just wanted to let you know that 'Show social media' workflow doesn't seem to be getting triggered by the wordpress site for the Waterloo project as no social links are displaying on the producer profile pages despite there being data in the Airtable base for these fields.  

<img width="1298" alt="Screenshot 2024-07-08 at 4 16 19 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/bb2ed70c-a875-426a-9b62-94e6e8119a92">

Also there is no history of executions for the that workflow in n8n.  Maybe this is something we can circle back once forking the components has been completed.  I just wanted to make a note of it now so it can be circled back to.

**Comment by karlafalk** [comment]
Hello @mkllnk just circling back to the above post about why we aren't getting social links appearing in the CAN directory?  It seems that maybe the social media workflow isn't being triggered by the code we have in the component:

<style>


custom-search-firstnationsled label {
  color: white !important;
}

custom-search-firstnationsled label:before {
  content: "Indigenous Led";
  color: black;
  display: block;
  position: absolute;
}
</style>

<script type="module" src="https://cdn.skypack.dev/@startinblox/core@0.19"></script>
<script type="module" src="https://cdn.skypack.dev/@startinblox/router@0.12"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@startinblox/component-ofn-rpp"></script>

<solid-ofn-rpp
  producers-src="https://api.regenerative.org.au/webhook/regen_CAN/producers"
  range-product-categories="https://api.regenerative.org.au/webhook/regen_CAN/produce_categories"
  range-producer-assurances="https://api.regenerative.org.au/webhook/regen_CAN/assurance_partners"
  
  uniq="directory"
  route-prefix="directory"
  ></solid-ofn-rpp>
/ <style>

Do you have any suggestions on how I might troubleshoot this?  Thanks!

**Comment by karlafalk** [comment]
Also @mkllnk I just had a general question - Are we able to change column headings in our Airtable base or would that unlink some of the workflows?  Just wondering if a change in name gets automatically updated in the n8n workflow?  Thanks!

**Comment by mkllnk** [comment]
I found some mismatches in the URLs of the social media endpoints. I hope that's fixed now.

**Comment by karlafalk** [comment]
Thanks @mkllnk for looking into this!  I have also been trying to fiddle with things to see if I could get it to work. It looks like I may have changed the wrong thing though and you changed it back.  As of this morning the social media links are still not showing on our wordpress site (but maybe we have to wait longer?? It has been ~3 hrs and there has been recent n8n executions, but sometimes it seems like it can take 1/2 day for changes to appear)...

It looks like this is the path for the social medias webhook: https://n8n.openfoodnetwork.org/webhook/b3c587b7-1fce-47c5-9f49-9371bf79bcee/regen_CAN/enterprises/:enterprise_id/social_medias/:social_media_id

And it seems the problem is that this webhook is not getting triggered at all, and it should be getting triggered in the other n8n workflows.  Specifically in the 'SIB workflow 3_Show producer'.  

Here are the things I tried changing (I don't really know what I am doing so didn't want to change too much!):

<img width="1557" alt="Screenshot 2024-08-08 at 6 45 55 AM" src="https://github.com/user-attachments/assets/9665f4fa-4fe3-4e6d-ae10-865ac2da127e">

<img width="2196" alt="Screenshot 2024-08-07 at 4 53 28 PM" src="https://github.com/user-attachments/assets/d17c42ba-c92c-4148-8c02-3cb2118a787f">

**Note:**  for the 'regen_CAN' I thought it was 'enterprises_CAN' in the webhook for social media, but now it looks like it is 'regen_CAN' (as above) so maybe you also changed this? Or maybe I was looking at the wrong thing!  

I am wondering if there is one last inconsistency: 
<img width="1530" alt="Screenshot 2024-08-08 at 6 55 40 AM" src="https://github.com/user-attachments/assets/d3393a37-9ef9-4ff4-93fb-9ca546f9bab4">

Should this tag be changed?

**Comment by karlafalk** [comment]
@mkllnk @David-OFN-CA Just flagging that this still is not working.  The social media workflow does get triggered now, which is good, but still no social media info is getting displayed on our wordpress site.  Also, it seems to only be working for only one enterprise (1 item), when there are 2 enterprises with social media info in the Airtable.  

<img width="1788" alt="Screenshot 2024-08-09 at 12 20 43 PM" src="https://github.com/user-attachments/assets/1ca2442a-6bd6-4783-b79b-52214d75e42d">

<img width="1442" alt="Screenshot 2024-08-09 at 12 21 21 PM" src="https://github.com/user-attachments/assets/2cf9762e-5ae7-4e70-af03-d94b4a8a08c2">

I am wondering if it has to do with this tag 'b3c587b7-1fce-47c5-9f49-9371bf79bcee'?  This tag appears in 3 places as far as I can tell (SIB workflow 3_Show producer - code & list social media nodes, and SIB workflow 9_Show social media - code nodes)  related to the social medias.  In some places it was as above,  in others it was 'b9c3687f-9f0f-4628-9bcc-f3331afb6fa8'.  I changed them all to 'b3c587b7-1fce-47c5-9f49-9371bf79bcee' to match the social medias webhook, as that made sense to me, but not sure if this was correct?  

I am not sure what else to try and will now be away till Sept.  Hopefully the source of the problem can be solved.  Thanks!

**Comment by David-OFN-CA** [comment]
Closing this issue as Maikel has addressed the social media workflow issue (see screen shot 1 / [link](https://waterlooregionfood.ca/staging/5285/regenerative-produce-portal-producer-details/@https%3A%2F%2Fapi.regenerative.org.au%2Fwebhook%2Fregen_CAN%2Fproducer%3Fid%3Drecf73vz5vjN5ztQN@)) and labels and headings for fiter menus are also resolved (see screenshot 2) - thanks all!


**Screenshot 1**

![Image](https://github.com/user-attachments/assets/a5a8b21f-5e1a-4c87-b970-8714090dae85)

**Screenshot 2**

![Image](https://github.com/user-attachments/assets/598bbc01-49d2-4a5d-9720-5621f1c0a9ae)
